-- ==================
-- Magnitude Analysis
-- ==================

-- Find total customers by countries

SELECT
	country,
	COUNT(customer_key) AS TotalCustomers
FROM dim_customers
GROUP BY country
ORDER BY TotalCustomers DESC;

-- Find total customers by genders

SELECT
	gender,
	COUNT(customer_key) AS TotalCustomers
FROM dim_customers
GROUP BY gender
ORDER BY TotalCustomers DESC;

-- Find the products by category

SELECT
	category,
	COUNT(product_key) AS TotalProducts
FROM dim_products
GROUP BY category
ORDER BY TotalProducts DESC;

-- What is the average costs in each category?

SELECT
	category,
	AVG(Cost) AS AverageCost
FROM dim_products
GROUP BY category
ORDER BY AverageCost DESC;

-- What is the total revenue generated for each category?

SELECT
	P.category,
	SUM(S.Sales_Amount) AS TotalAmount
FROM fact_sales AS S
JOIN dim_products AS P
ON S.product_key = P.product_key
GROUP BY P.category
ORDER BY TotalAmount DESC;

-- Find total revenue is generated by each customer

SELECT
	customer_key,
	SUM(Sales_Amount) AS TotalAmount
FROM fact_sales
GROUP BY customer_key
ORDER BY TotalAmount DESC;

-- What is the distribution of sold items across countries?

SELECT
	C.country,
	SUM(S.quantity) AS TotalQuantity
FROM fact_sales AS S
JOIN dim_customers AS C
ON S.customer_key = C.customer_key
GROUP BY C.country
ORDER BY TotalQuantity DESC;